spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/saude_recife
spring.datasource.username=saude_user
spring.datasource.password=saude_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=chave-secreta-temporaria-dev-troque-em-producao-minimo-32-caracteres
jwt.expiracao-ms=86400000